### ISSUE TITLE
Add client manager to access available client dynamically

### ISSUE THREAD

**Issue by ajstevens** [Drenso/symfony-oidc#13]
I am trying to have multiple firewalls in Symfony with each their own OIDC config. 
In the firewall I specify the client: 

```yaml

        rkd:
            pattern: ^/rkd
            lazy: true
            provider: oidc_user_provider
            oidc:
                client: rkd
                user_identifier_property: 'email'
                login_path: '/rkd/login_oidc'
                check_path: '/rkd/login_check'
            logout:
                path: logout

        admin:
            pattern: ^/admin
            lazy: true
            provider: oidc_user_provider
            oidc:
                client: admin
                user_identifier_property: 'email'
                login_path: '/admin/login_oidc'
                check_path: '/admin/login_check'
            logout:
                path: logout

```
I have multiple clients defined, which I can load with DI if i know the client name in the DI OIDCClientInterface the login url.  But I would like to get a specific named client dynamically. 
```
    default: 
      # Required OIDC client configuration
      well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
      client_id: '%env(OIDC_CLIENT_ID)%'
      client_secret: '%env(OIDC_CLIENT_SECRET)%'
      redirect_route: '/rkd/login_check'

    admin: 
      # Required OIDC client configuration
      well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
      client_id: 'cap_rkd'
      client_secret: '%env(OIDC_CLIENT_SECRET)%'
      redirect_route: '/test/login_check'
```

The problem is with starting the OIDC, I always get the default client in the login controller. 
```php
  #[Route('/{slug}/login_oidc', name: 'login_oidc')]
  #[IsGranted('PUBLIC_ACCESS')]
    public function surfconext(Organisation $organisation, OidcClientInterface $client): RedirectResponse
    {
        return $client->generateAuthorizationRedirect();   
    }
```

How can I best get the specific client in this case?
