### ISSUE TITLE
How to save the identity provider used for registration?

### ISSUE THREAD

**Issue by tobias47n9e** [Drenso/symfony-oidc#22]
In the `OidcUserProviderInterface` there is a function `ensureUserExists` where the user is either resolved or created. If I use multiple OIDC providers, I am not sure how to save the provider that the user used in this function (e.g. Google, Twitter, ...). Is it possible to access that value in this function or in another place?

These are the identifiers which I would need to access:

```yaml
drenso_oidc:
    clients:
        google: 
            ...
        twitter: 
            ...
```

**Comment by bobvandevijver** [comment]
Not directly, as those client ids are really only used for service registration and autoloading. 

Are you using different firewalls with the different clients? If so, you could create dedicated user providers, which should look something like the following:

```yaml
# security.yaml
security:
  providers:
    google_provider: App\Security\UserProvider\GoogleUserProvider
    twitter_provider: App\Security\UserProvider\TwitterUserProvider

  firewalls:
    google:
      oidc: ~
      provider: google_provider 
    twitter:
      oidc: ~
      provider: twitter_provider 
```

```php
class GoogleUserProvider extends YourUserProvider {
  final public const CLIENT = 'google';
}

Otherwise please share your security configuration, maybe I can see a bit more from that.
