### ISSUE TITLE
Add support for AccessTokenHandler (Symfony 6.2)

### ISSUE THREAD

**Issue by rvmourik** [Drenso/symfony-oidc#26]
In Symfony 6.2 there is a new class `AccessTokenHandler`, which allow you to implement support for checking a token which was provided through a Header, Request Body or Querystring.

Would you accept a PR which adds a AccessTokenHandler which can be activated through:

```yaml
# config/packages/security.yaml
security:
    firewalls:
        main:
            oidc: ~
            access_token:
                token_handler: Drenso\OidcBundle\Security\OidcAccessTokenHandler
```

The `OidcAccessTokenHandler` will contain the code to check if the passed Token is valid against the active Oidc client for this particular firewall. 

This implementation then can be used for example if the Symfony Application contains a REST api and the API client sends the token to the SF REST API. The AccessTokenHandler will then check if the passed token is still valid.

It would need a disclaimer it is only usable with SF 6.2
