### ISSUE TITLE
Invalid session state

### ISSUE THREAD

**Issue by r3dge** [Drenso/symfony-oidc#32]
Hi,

Thanks for this bundle which is veru usefull !

I get an exception when trying to set up a second client.

drenso_oidc.yaml : 

```
drenso_oidc:
    #default_client: default # The default client, will be aliased to OidcClientInterface
    clients:
        default: # The client name, each client will be aliased to its name (for example, $defaultOidcClient)
            # Required OIDC client configuration
            well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
            client_id: '%env(OIDC_CLIENT_ID)%'
            client_secret: '%env(OIDC_CLIENT_SECRET)%'
            # Extra configuration options
            redirect_route: '/oidc/login_check'
            #custom_client_headers: []

        # Add any extra client
        another_client: # Will be accessible using $linkOidcClient
            well_known_url: 'http://localhost:8080/realms/my-realm/.well-known/openid-configuration'
            client_id: 'another_client'
            client_secret: 'hA5OUlkzEFX63Qhmf5jFVdfmT9vDgZkX'
```

When i am connecting with the "default" client it works. But when i'm working with "another_client" i get an exception : 

```
[2023-03-08T16:26:01.252978+01:00] security.INFO: Authenticator failed. {"exception":"[object] (Drenso\\OidcBundle\\Security\\Exception\\OidcAuthenticationException(code: 0): Invalid session state at /var/www/html/fizyou/vendor/drenso/symfony-oidc-bundle/src/OidcClient.php:90)","authenticator":"Drenso\\OidcBundle\\Security\\OidcAuthenticator"} []
[2023-03-08T16:26:01.253267+01:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/login"} []
```

Here is my config : 

```
security:
    #enable_authenticator_manager: true
    providers:
        #app_user_provider: 
            #entity: {class: App\Entity\User, property: email}
        oidc_provider:
            id: App\Security\OpenIdConnectUserProvider
    password_hashers:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false       
            
        main:
            lazy: true
            provider: oidc_provider
            custom_authenticators: 
                - App\Security\LoginFormAuthenticator

            user_checker: App\Security\UserChecker
            form_login: ~
            oidc:
                user_identifier_property: email
                check_path: /oidc/login_check
            entry_point: form_login
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login
            # configure the maximum login attempts in a custom period of time
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'
            remember_me: 
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                path: /
                secure: true
                remember_me_parameter: _remember_me`
```

My controller : 

```php
    #[Route('/oidc/login/{entityId}', name: 'oidc_login')]
    #[IsGranted('PUBLIC_ACCESS')]
    public function surfconext(OidcClientLocator $clientLocator, OidcClientInterface $oidcClient, Request $request, string $entityId): RedirectResponse
    {
      // Redirect to authorization @ OIDC provider
      //return $oidcClient->generateAuthorizationRedirect(); 
      return $clientLocator->getClient($entityId)->generateAuthorizationRedirect();
    }

    #[Route('/oidc/login_check', name: 'oidc_login_check')]
    #[IsGranted('PUBLIC_ACCESS')]
    public function checkLogin(OidcClientInterface $oidcClient, Request $request, string $code, string $state): RedirectResponse
    {

    }
```

Do you have any idea how to fix this issue ?

Thank you !

**Comment by bobvandevijver** [comment]
Your firewall is configured to use the default OIDC client, but you're trying to authenticate using your second client. That won't work: the default client doesn't know about the state, which is what it is telling you in the logged message. We currently do not support this scenario because Symfony also doesn't support it natively, see #29 for some explanation and for some possible solutions.

**Comment by r3dge** [comment]
Ok thank you for this feedback. I will give a try to custom AuthenticatorFactory based on OidcFactory. Do you have an idea how i can register a new AuthenticatorFactory in the application ? IS it a basic service or should I add some specific configuration ? There is no symfony documentation on that topic.
Many thanks.

**Comment by bobvandevijver** [comment]
Basically the same as it is done in `DrensoOidcBundle`, but then in your apps `build` method that can be found in the `Kernel.php`.

https://github.com/Drenso/symfony-oidc/blob/ca0eb83d8235d5f35d9b3428f679bf7085e9f155/src/DrensoOidcBundle.php#L17

https://github.com/Drenso/symfony-oidc/blob/ca0eb83d8235d5f35d9b3428f679bf7085e9f155/src/DrensoOidcBundle.php#L19

**Comment by r3dge** [comment]
Many thanks for your support.

I post below the detailled solution that could help someone that want to have many SSO authenticator in the same app and in the same firewall.

1. Copy the OidcFactory from the bundle to your app and rename it as CustomOidcFactory.
2. Modify the kernel.php by adding this method (to register the factory): 

`protected function build(ContainerBuilder $container)`
`{`
`    $extension = $container->getExtension('security');`
`    $extension->addAuthenticatorFactory(new CustomOidcFactory());`
`}`
3. In CustomOidcFactory, modify the createAuthenticator method to load the client list : 

`$configValues = Yaml::parse(file_get_contents("path/to/file/drenso_oidc.yaml));`

4. and push the code of the method inside a foreach loop : 

` foreach($configValues['drenso_oidc']['clients'] as $clientName=>$clientParams){`
`}`
5. Modify the return of the method which should return the list of authenticatorId as array.

In that way each client in the drenso_oidc.yaml could connect with sso.

++

**Comment by bobvandevijver** [comment]
It should be easier to extend the factory instead and only override the `getKey` method to something custom. That way, you can add that custom key to your authentication configuration and create a dedicated configuration for that particular client. That would also enable you to use dedicated return paths for each client, which makes the authentication process more efficient and easier to maintain.

**Comment by r3dge** [comment]
thanks for this feedback. I will give a try.

**Comment by bobvandevijver** [comment]
I am closing this due to inactivity, if the issue persists please feel free to reopen.

**Comment by SCIF** [comment]
I've got `There is currently no session available` exception on visit `/oidc/sso`.
@bobvandevijver , could you please advise how to debug my case?

![image](https://github.com/user-attachments/assets/670fad02-d57c-47e0-a62e-78d28f6d23a0)


`security.yaml`:
```
security:
    providers:
        oidc_user_provider:
            id: My\Vendor\UserProvider
    firewalls:
        oidc:
            pattern: ^/
            provider: oidc_user_provider
            oidc:
                login_path: /oidc/sso
                check_path: /oidc/redirect
```

`drenso_oidc.yaml`:
```
drenso_oidc:
    #default_client: default # The default client, will be aliased to OidcClientInterface
    clients:
        default: # The client name, each client will be aliased to its name (for example, $defaultOidcClient)
            # Required OIDC client configuration
            well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
            client_id: '%env(OIDC_CLIENT_ID)%'
            client_secret: '%env(OIDC_CLIENT_SECRET)%'
```
controller:
```
final readonly class OpenIdConnectSSO
{
    #[Route(path: '/oidc/sso', name: 'oidc_sso', methods: ['POST'])]
    public function __invoke(
        OidcClientInterface $client,
    ): JsonResponse {
dd($client->generateAuthorizationRedirect());
```
