### ISSUE TITLE
No route found for "POST https://my-domain/login_check" (from "https://identity-provider.domain/")

### ISSUE THREAD

**Issue by svinohod** [Drenso/symfony-oidc#43]
I get in my Symfony `No route found for "POST https://my.domain/login_check" (from "https://identity-provider.domain/")` if my identity-provider redirects back to the redirect_uri (https://my.domain/login_check) including a code parameter. It is OpenID Connect Code Flow step 5. 

Symfony: 6.3
drenso/symfony-oidc-bundle: 2.12.0

my  security.yaml:
```
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        oidc_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            oidc: ~

            lazy: true
            provider: oidc_user_provider

    access_control:

```

my drenso_oidc.yaml :
```
drenso_oidc:
    #default_client: default # The default client, will be aliased to OidcClientInterface
    clients:
        default: # The client name, each client will be aliased to its name (for example, $defaultOidcClient)
            # Required OIDC client configuration
            well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
            client_id: '%env(OIDC_CLIENT_ID)%'
            client_secret: '%env(OIDC_CLIENT_SECRET)%'
```

my LoginController.php:
```
class LoginController extends AbstractController
{
    /**
     * This controller forwards the user to the OIDC login
     * @throws OidcException
     */
    #[Route('/login_oidc', name: 'login_oidc')]
    #[IsGranted('PUBLIC_ACCESS')]
    public function loginOidc(OidcClientInterface $oidcClient): RedirectResponse
    {
        // Redirect to authorization @ OIDC provider
        return $oidcClient->generateAuthorizationRedirect('login', ['openid'], false, ['response_mode' => 'form_post']);
    }
}
```
