### ISSUE TITLE
JWT Decode missing on UserInfo

### ISSUE THREAD

**Issue by AL-FAW** [Drenso/symfony-oidc#63]
Hi,

First of all, I'd like to warn that I'm very new to OpenID implementations, and as such, I might have failed to properly understand how it works and this issue could be a pebkac in this instance. If it is, my apologies.

That being said : I am having an issue with the library when using the `openid` scope, specifically within the OidcAuthenticator and the OidcClient. I'm running version 3.1.0.

Here is the`OidcClient::retrieveUserInfo` method.
 
 ```php
   public function retrieveUserInfo(OidcTokens $tokens): OidcUserData
  {
    // Set the authorization header
    $headers = ["Authorization: Bearer {$tokens->getAccessToken()}"];

    // Retrieve the user information and convert the encoding to UTF-8 to harden for surfconext UTF-8 bug
    $jsonData = $this->urlFetcher->fetchUrl($this->getUserinfoEndpoint(), null, $headers);
    $jsonData = mb_convert_encoding($jsonData, 'UTF-8');

    // Read the data
    $data = json_decode($jsonData, true);

    // Check data due
    if (!is_array($data)) {
      throw new OidcException('Error retrieving the user info from the endpoint.');
    }

    return new OidcUserData($data);
  }
 ```

As you can see, the method expects the returned data to be available immediately, and tries to json_decode it. However, as per the [OpenID specs of the UserInfo response](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse), this data might actually be encoded within a JWT as well. If it is, the json_decode will return `null` (because we are passing it the encoded JWT, and not actual json data), which will then trigger the throw, and making the whole auth fail despite my provider sending back the correct data (I've decoded the response manually for debug purposes).

I thought that maybe I was missing something and that the `user_identifier_from_idtoken` config value had to be set to `true` when using encoded `openid`, but even so, given how the `OidcAuthenticator::authenticate` method is implemented, the `OidcClient::retrieveUserInfo` will be called regardless and will fail anyway.
``` php
public function authenticate(Request $request): Passport
  {
    try {
      // Try to authenticate the request
      $authData = $this->oidcClient->authenticate($request);

      // Retrieve the user data with the authentication data
      $userData = $this->oidcClient->retrieveUserInfo($authData);

      // Look for the user identifier in either the id_token or the userinfo endpoint
      if ($this->userIdentifierFromIdToken) {
        $userIdentifier = OidcJwtHelper::parseToken($authData->getIdToken())
          ->claims()
          ->get($this->userIdentifierProperty);
      } else {
        $userIdentifier = $userData->getUserDataString($this->userIdentifierProperty);
      }

      [Rest of the code, irrelevent to my current issue]

      return $passport;
    } catch (OidcException $e) {
      throw new OidcAuthenticationException('OIDC authentication failed', $e);
    }
  }
  ```

So, ultimately, the issue I'm raising is : shouldn't the `OidcClient::retrieveUserInfo` method handle having an JWT-encoded response ?

**Comment by bobvandevijver** [comment]
Relevant snippets from the specification:
> The UserInfo Claims MUST be returned as the members of a JSON object unless a signed or encrypted response was requested during Client Registration.
> If the UserInfo Response is signed and/or encrypted, then the Claims are returned in a JWT and the content-type MUST be application/jwt.

Which means that you are right, it is indeed possible that the UserInfo response is not a plain JSON responseL it can be a signed and/or encrypted JWT instead. But, this should only be done when requested during client registration, so this would be something you should be able to change for your client. At this time we do not support anything else than an unencrypted JSON UserInfo response.

Are you able to change your client configuration to not sign/encrypt the UserInfo endpoint? Which provider do you use?

**Comment by bobvandevijver** [comment]
Ah, you are confusing the ID Token endpoint and the UserInfo endpoint. Those are actually two completely different things: the ID token is always a JWT and that is retrieved and fully handled (in the `authenticate` method) before requesting the user info.

For Safenet, from what I can find, you should be able to disable the "userinfo signature algorithm". See https://thalesdocs.com/sta/operator/applications/apps_oidc/index.html#configure-the-oidc-application (but I have no experience with this provider whatsoever).

**Comment by AL-FAW** [comment]
I see. It being mentioned in the "Introduction" section of the specs and not in the Authentication part, I figured it was generic to the entire flow. Thank you for clearing that up.

Thanks a lot for the pointers regarding Safenet. I don't have access to the provider itself (my client is the one setting it up, I'm merely plugging to it), but I'll see about contacting them if need be.

Thank you again for everything, and sorry about the confusion.

**Comment by nuryagdym** [comment]
I faced the same issue with a different provider, this provider sent user info as JWT string 
and also for `grant_type= authorization_code` request it required `client_id` to be sent in the request body, although it is already sent in the header. So I needed to remove this line:
https://github.com/Drenso/symfony-oidc/blob/66af842a3064578a02bd24699ccc88e8da450d49/src/OidcClient.php#L494

As this changes required change in private methods in `OidcClient`  I decided to create new custom client to override existing one.

I don't know if there are better way to override the bundle service but I found did this way:

`/config/drenso_oidc.yaml`
```yaml
drenso_oidc:
    default_client: "default" # The default client, will be aliased to OidcClientInterface
    clients:
        default: # The client name, each client will be aliased to its name (for example, $defaultOidcClient)
            # Required OIDC client configuration
            well_known_url: '%env(OIDC_WELL_KNOWN_URL)%'
            client_id: '%env(OIDC_CLIENT_ID)%'
            client_secret: '%env(OIDC_CLIENT_SECRET)%'
            disable_nonce: false
```
`/config/services.yaml`
```yaml
services:
    drenso.oidc.client.default: #override existing client defined in drenso_oidc.yaml
        class: App\Security\CustomOidcClient # my custom client
        arguments:
            $requestStack: '@request_stack'
            $httpUtils: '@security.http_utils'
            $wellKnownCache: '@Symfony\Contracts\Cache\CacheInterface'
            $urlFetcher: '@drenso.oidc.url_fetcher.default'
            $sessionStorage: '@drenso.oidc.session_storage.default'
            $jwtHelper: '@drenso.oidc.jwt_helper.default'
            $wellKnownUrl: '%env(OIDC_WELL_KNOWN_URL)%'
            $wellKnownCacheTime: 3600
            $clientId: '%env(OIDC_CLIENT_ID)%'
            $clientSecret: '%env(OIDC_CLIENT_SECRET)%'
            $redirectRoute: 'https://identity-gateway.docker.localhost/oidc/login-check'
            $rememberMeParameter: _remember_me
```

and copied contents of `Drenso\OidcBundle\OidcClient` into `App\Security\CustomOidcClient` and did necessary changes.

our custom instance will be now injected to `Drenso\OidcBundle\Security\OidcAuthenticator`.

Although we did not need now client configuration in `drenso_oidc.yaml`, we need it so that bundle create services such as
`@drenso.oidc.session_storage.default`, `@drenso.oidc.url_fetcher.default`, `@drenso.oidc.jwt_helper.default`.
