### ISSUE TITLE
Readme documentation about logout is confusing

### ISSUE THREAD

**Issue by nuryagdym** [Drenso/symfony-oidc#67]
For logout there is this information in README:
**_Example: custom logout path_**

```yaml
security:
  firewalls:
    main:
      logout:
        target: /my_custom_target_path
      oidc:
        enable_end_session_listener: true
```

I don't what is the purpose of this example. 
But for **custom logout path** the parameter that needs to be set is `logout.path` instead of `logout.target`.
If we mean custom target path the title needs to be changed to **_Example: custom logout target path_**
