### ISSUE TITLE
Feature request: Multiple authenticator keys

### ISSUE THREAD

**Issue by welcoMattic** [Drenso/symfony-oidc#79]
As described here, https://github.com/Drenso/symfony-oidc/issues/29#issuecomment-1378373774, it could be helpful to provide multiple authenticator keys to implement login from different services.

Let's get an exemple:

I need to secure a part of my app behind a firewall named `bunker`. To access this part, I provide the users 2 different ways to login (let's say Keycloak and MS EntraID).

```yaml
        keycloak:
            pattern: ^/bunker
            provider: users
            logout: true
            oidc:
                client: keycloak
                login_path: /keycloak_login
                check_path: /keycloak_login_check
                failure_path: /keycloak_login_failure
                enable_end_session_listener: true
                user_identifier_from_idtoken: false

        entra:
            pattern: ^/bunker
            provider: agents
            logout: true
            oidc:
                client: entra
                login_path: /entra_login
                check_path: /entra_login_check
                failure_path: /entra_login_failure
                enable_end_session_listener: true               
                user_identifier_from_idtoken: true
```

The problem here, is I have 2 firewalls, and Symfony can not decide which one to use, so it uses the first one by default.

The solution could be something like in https://github.com/hwi/HWIOAuthBundle/blob/master/docs/3-configuring_the_security_layer.md#b-configure-the-oauth-firewall

```yaml
        bunker:
            pattern: ^/bunker
            provider: users
            logout: true
            oidc:
                providers:
                    keycloak:
                        client: keycloak
                        login_path: /keycloak_login
                        check_path: /keycloak_login_check
                        failure_path: /keycloak_login_failure
                        enable_end_session_listener: true
                        user_identifier_from_idtoken: false
                    entra:
                        client: entra
                        login_path: /entra_login
                        check_path: /entra_login_check
                        failure_path: /entra_login_failure
                        enable_end_session_listener: true               
                        user_identifier_from_idtoken: true
```

Let me know if this is something you want to add in the bundle or not. I would be happy to help to contribute.
