### ISSUE TITLE
Proposal for Token Exchange/AccessTokenHandlerInterface Symfony Integration

### ISSUE THREAD

**Issue by dbollaer** [Drenso/symfony-oidc#88]
Hello,

I am looking into configuring token exchange.
I am having a bit of difficulty, due to my limited knowledge on the topic, but I am confident I’ll figure it out.

The reason I am contacting you is to ask for feedback on a proposal.
I would like to implement `TokenExchange` as a service.

```yaml
drenso_oidc:
    # token_exchange: default # The default tokenExchange, will be aliased to OidcTokenExchangeInterface
    token_exchanges:
        default:
            scope:
            audience:
            client: # optional, uses default
```

```php
interface OidcTokenExchangeInterface {
    public function getAccessToken(): string;
}
```

I will also have to make a separate PR, because the current implementation does not fully comply with the standards.
The `subject_token_type` is not being passed along.
I am expecting subject_token_type to be filled in with urn:ietf:params:oauth:token-type:access_token.

References:

* [RFC 8693 - Token Exchange Request](https://datatracker.ietf.org/doc/html/rfc8693#name-request)
* [RFC 8693 - Example Token Exchange](https://datatracker.ietf.org/doc/html/rfc8693#name-example-token-exchange)

```
subject_token_type
REQUIRED. An identifier, as described in [Section 3](https://datatracker.ietf.org/doc/html/rfc8693#TokenTypeIdentifiers), that indicates the type of the security token in the subject_token parameter.
```

I am concerned this might break the original contributor’s guide:
[https://github.com/Drenso/symfony-oidc/pull/66](https://github.com/Drenso/symfony-oidc/pull/66)

Lastly, I would also like to use this library in my backend API.
Should I create my own `AccessTokenHandlerInterface` that uses the introspection endpoint?

Thank you for your advice.
It may be a couple of weeks before I can work on this, so please take your time.
